id: I9FA90754
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-05T09:26:53+00:00'
last_modified: '2022-06-16T05:24:19.421285+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD104698
  title: གྲོ་ལུང་པ་བློ་གྲོས་འབྱུང་གནས་ཀྱི་གསུང་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    402F:
      image_group_id: I1KG5853
      title: ''
      total_pages: ''
      order: 1
      base_file: 402F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
